language: objective-c
xcode_project: CleanroomASL.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build 2>&1 | tee "CleanroomASL-iOS-build.log" | xcpretty ) && rm "CleanroomASL-iOS-build.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test 2>&1 | tee "CleanroomASL-iOS-test.log" | xcpretty ) && rm "CleanroomASL-iOS-test.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-OSX -destination 'platform=macOS' -destination-timeout 300 clean build 2>&1 | tee "CleanroomASL-macOS-build.log" | xcpretty ) && rm "CleanroomASL-macOS-build.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-OSX -destination 'platform=macOS' -destination-timeout 300 test 2>&1 | tee "CleanroomASL-macOS-test.log" | xcpretty ) && rm "CleanroomASL-macOS-test.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build 2>&1 | tee "CleanroomASL-tvOS-build.log" | xcpretty ) && rm "CleanroomASL-tvOS-build.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test 2>&1 | tee "CleanroomASL-tvOS-test.log" | xcpretty ) && rm "CleanroomASL-tvOS-test.log"
  - ( set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build 2>&1 | tee "CleanroomASL-watchOS-build.log" | xcpretty ) && rm "CleanroomASL-watchOS-build.log"

after_failure:
  - test -f "CleanroomASL-iOS-build.log" && tail -n 2500 "CleanroomASL-iOS-build.log"
  - test -f "CleanroomASL-iOS-test.log" && tail -n 2500 "CleanroomASL-iOS-test.log"
  - test -f "CleanroomASL-iOS-test.log" && LINE_BEFORE=`cat "CleanroomASL-iOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomASL-iOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomASL-macOS-build.log" && tail -n 2500 "CleanroomASL-macOS-build.log"
  - test -f "CleanroomASL-macOS-test.log" && tail -n 2500 "CleanroomASL-macOS-test.log"
  - test -f "CleanroomASL-macOS-test.log" && LINE_BEFORE=`cat "CleanroomASL-macOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomASL-macOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomASL-tvOS-build.log" && tail -n 2500 "CleanroomASL-tvOS-build.log"
  - test -f "CleanroomASL-tvOS-test.log" && tail -n 2500 "CleanroomASL-tvOS-test.log"
  - test -f "CleanroomASL-tvOS-test.log" && LINE_BEFORE=`cat "CleanroomASL-tvOS-test.log" | grep -n "IDETestOperationsObserverDebug. Writing diagnostic log for test session to." | awk -F':' '{print $1}'` && LINE=`expr $LINE_BEFORE + 1` && LOG_FILE=`head -n $LINE "CleanroomASL-tvOS-test.log" | tail -n 1` && cat "$LOG_FILE"
  - test -f "CleanroomASL-watchOS-build.log" && tail -n 2500 "CleanroomASL-watchOS-build.log"

