language: objective-c
xcode_project: CleanroomASL.xcodeproj
osx_image: xcode8

git:
  depth: 1
  submodules: false

before_install:
  - git submodule update --init

install:
  - gem install xcpretty

script:
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 clean build | tee "CleanroomASL-iOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-iOS -destination 'platform=iOS Simulator,OS=10.0,name=iPhone 6s Plus' -destination-timeout 300 test | tee "CleanroomASL-iOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-OSX -destination 'platform=macOS' -destination-timeout 300 clean build | tee "CleanroomASL-macOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-OSX -destination 'platform=macOS' -destination-timeout 300 test | tee "CleanroomASL-macOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 clean build | tee "CleanroomASL-tvOS-build.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-tvOS -destination 'platform=tvOS Simulator,OS=10.0,name=Apple TV 1080p' -destination-timeout 300 test | tee "CleanroomASL-tvOS-test.log" | xcpretty
- set -o pipefail && xcodebuild -project CleanroomASL.xcodeproj -configuration Release ONLY_ACTIVE_ARCH=YES -scheme CleanroomASL-watchOS -destination 'platform=watchOS Simulator,OS=3.0,name=Apple Watch - 42mm' -destination-timeout 300 clean build | tee "CleanroomASL-watchOS-build.log" | xcpretty

after_failure:
- [ -f "CleanroomASL-iOS-build.log" ] && cat "CleanroomASL-iOS-build.log"
- [ -f "CleanroomASL-iOS-test.log" ] && cat "CleanroomASL-iOS-test.log"
- [ -f "CleanroomASL-macOS-build.log" ] && cat "CleanroomASL-macOS-build.log"
- [ -f "CleanroomASL-macOS-test.log" ] && cat "CleanroomASL-macOS-test.log"
- [ -f "CleanroomASL-tvOS-build.log" ] && cat "CleanroomASL-tvOS-build.log"
- [ -f "CleanroomASL-tvOS-test.log" ] && cat "CleanroomASL-tvOS-test.log"
- [ -f "CleanroomASL-watchOS-build.log" ] && cat "CleanroomASL-watchOS-build.log"

